### ISSUE TITLE
Mapa Mental 

### ISSUE THREAD

**Issue by MarcoRg06** [SistemasTecTlaxiaco/actividad-4-mapa-mental-MarcoRg06#1]
Nombre: Marco Uriel Rosas Garcia 
Grupo: 1 BS
[trabajo_MapaMental22.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-MarcoRg06/files/9612460/trabajo_MapaMental22.pdf)

**Comment by Daniel-Velasco-Lopez** [comment]
De la actividad 4
Obtuviste un 18.2% del 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
